version: '3'
services:
    app:
        container_name: "messagesReducer-app"
        build: .
        links:
            - db
        ports:
            - 80:5002
    db:
        container_name: "messagesReducer-db"
        image: mongo
        ports:
            - 27017:27017
