apiVersion: v1
kind: Service
metadata:
  name: backend-server-service
  labels:
    app: messenger.backend-server
spec:
  ports:
    - protocol: TCP
      port: 5000
  selector:
    app: messenger.backend-server
